### ISSUE TITLE
Failed to fetch recommendations for a specific user

### ISSUE THREAD

**Issue by mislav** [mislav/movieapp#5]
@norbert: A friend has reported that she's unable to see her movies. I looked in the exceptions log and it seems the recommendations service was returning HTTP 500s:

```
user_id: 4f9976538923a20001000007

Backtrace:
app/models/recommendations.rb 52 in `block in fetch_recommendations'
app/models/recommendations.rb 48 in `fetch_recommendations'
app/models/recommendations.rb 13 in `recommended_movie_ids'
app/models/recommendations.rb 9 in `load_movies'
app/models/recommendations.rb 17 in `movies'
app/views/users/_recommendation_notice.html.erb 1 in `_app_views_users__recommendation_notice_html_erb___399078311213063861_44540640'
app/views/users/show.html.erb 43 in `_app_views_users_show_html_erb___2599279801710922496_57705480'
lib/api_runtime_stats.rb 17 in `cleanup_view_runtime'
```

This feels a little bit like #4 but is caused specifically by recommendation service and not by metadata services.

I'm going to attempt a workaround by rescuing any HTTP errors and skipping rendering of the recommendations partial.

**Comment by mislav** [comment]
Recommendation service is now fixed but I need to put extra work in re-training the model occasionally.

**Comment by Prasath18** [comment]
Failed to get recommendations for user = 0057F000000ZpOfQAK --- verify that the user has favorited a property and then relearn in PIO
